language: php

matrix:
    include:
        - php: 5.5
          env: dependencies=highest
        - php: 5.6
          env: dependencies=highest
        - php: 7.0
          env: dependencies=highest
        - php: hhvm
          env: dependencies=highest
        - php: hhvm
          env: dependencies=lowest
    allow_failures:
        - php: hhvm
          env: dependencies=lowest
        - php: 7.0
          env: dependencies=highest

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - composer self-update -q

install:
    - if [ "$dependencies" = "lowest" ]; then composer install --prefer-lowest --no-interaction; fi;
    - if [ "$dependencies" = "highest" ]; then composer install --no-interaction; fi;
    - composer show -i
    - if [ -z "$dependencies" ]; then composer install --no-interaction; fi;
    - composer show -i

script:
    - vendor/phpunit/phpunit/phpunit

