language: php

sudo: false

matrix:
    include:
        - php: 5.5
          env: dependencies=lowest
        - php: 5.5
          env: dependencies=highest
        - php: 5.6
          env: dependencies=lowest
        - php: 5.6
          env: dependencies=highest
        - php: 7.0
          env: dependencies=lowest
        - php: 7.0
          env: dependencies=highest
        - php: hhvm
          env: dependencies=highest
    allow_failures:
        - php: hhvm
    fast_finish: true

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - composer self-update -q

install:
    - if [ -z "$dependencies" ]; then travis_retry composer --prefer-source install --no-interaction; fi;
    - if [ "$dependencies" = "lowest" ]; then travis_retry composer --prefer-source update --prefer-lowest --no-interaction; fi;
    - if [ "$dependencies" = "highest" ]; then travis_retry composer --prefer-source update --no-interaction; fi;
    - composer show -i

script:
    - vendor/phpunit/phpunit/phpunit
