language: php

matrix:
    include:
        - php: 5.6
          env: deps=high
        - php: 7.0
          env: deps=high
        - php: hhvm
          env: deps=high
        - php: 5.6
          env: deps=low
        - php: 7.0
          env: deps=low
        - php: hhvm
          env: deps=low
    allow_failures:
        - php: 5.6
          env: deps=low
        - php: hhvm
          env: deps=low

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - composer self-update -q

install:
    - if [ -z "$deps" ]; then composer install; fi;
    - if [ "$deps" = "low" ]; then php -d memory_limit=-1 $(which composer) update --no-interaction --prefer-lowest; fi;
    - if [ "$deps" = "high" ]; then php -d memory_limit=-1 $(which composer) update --no-interaction; fi;

script:
    - phpunit

