language: php

matrix:
    include:
        - php: 5.6
          env: deps=low
        - php: 5.6
          env: deps=high
        - php: 7.0
          env: deps=low
        - php: 7.0
          env: deps=high
        - php: hhvm
          env: deps=low
        - php: hhvm
          env: deps=high
    allow_failures:
        - php: 5.6
          env: deps=low
        - php: 7.0
          env: deps=low
        - php: hhvm
          env: deps=low
        - php: hhvm
          env: deps=high

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php --quiet

install:
    - if [ -z "$deps" ]; then composer install; fi;
    - if [ "$deps" = "low" ]; then php -d memory_limit=-1 composer.phar update --no-interaction --prefer-lowest; fi;
    - if [ "$deps" = "high" ]; then php -d memory_limit=-1 composer.phar update --no-interaction; fi;

script:
    - phpunit

